### ISSUE TITLE
$target.retrieve('bootstrap:carousel')[to]() is undefined

### ISSUE THREAD

**Issue by HeyWrecker** [jwestbrook/bootstrap-prototype#1]
Hi Jason,

I found your port of Bootstrap and let me say thank you! We're stuck on a legacy system using Prototype / Sciptaculous, but trying to move forward with some newer CMS templates and this seems to be the only way I can get things to play nicely.

That being said, I did run into an issue when trying to implement the carousel. I'm using Prototype 1.7.1.0 and Scriptaculous 1.9.0 in the head of my page and the following files in the footer (in this order) for testing:
- bootstrap_prototype.js
- bootstrap-transition_prototype.js
- bootstrap-dropdown_prototype.js
- bootstrap-carousel_prototype.js

Whenever I click on the "next" or "previous"  carousel navs, I get the subject message in my Firebug log.

Am I doing something incorrectly in my implementation? Should I revert to an older version of the Prototype/Sciptaculous combination? Any help you might provide would be very much appreciated.

Thanks Jason!

Best Regards,

Rick Zawadzki

**Comment by jwestbrook** [comment]
You shouldn't need 
- bootstrap-transition_prototype.js
- bootstrap-dropdown_prototype.js
- bootstrap-carousel_prototype.js

if you have bootstrap_prototype.js on the page as it includes all of the components in one file

Can you post the HTML code where the carousel is defined?

The error is referring to the actual left and right html elements - make sure you have `href="#carouselid"` or `data-target="#carouselid"` on both of them

I have a testing ground where I implemented all of the components

http://www.cwaadmin.com/bootstrap/

**Comment by HeyWrecker** [comment]
Hey Jason,

Thanks for taking the time to get back to me. You know what, complete oversight on my part. The carousel I was implementing had a hidden mobile version so the IDs were conflicting. Sorry to trouble you. 

Best regards,

Rick

**Comment by jwestbrook** [comment]
No worries - I'm glad that others are using it.

**Comment by HeyWrecker** [comment]
Hi Jason,

Thanks again for your help earlier. I had checked out your test page and
it's been a great resource. However, I am running into a problem
implementing a responsive nav. I'm not quite sure what the issue is, but
when I collapse my browser, the nav button that should drop down a list of
the menu items simply does not work. Is it something I need to manually
instantiate when using the ported Bootstrap library?

Thanks Jason!

Rick

**Comment by jwestbrook** [comment]
I tried to make the implementation as similar as possible to the original implementation of all the Javascript Components in Bootstrap. Check to make sure the drop downs have the correct classes/attributes on them to trigger the javascript to render them as drop downs. On the sample page the `<a>`'s have an attribute `[data-toggle="dropdown"]` on them that the javascript is looking for to trigger.

let me know if that works for you and if you have any other problems

**Comment by HeyWrecker** [comment]
Good morning Jason,

Thanks again for the reply. So far I've had no problems with the
dropdowns.  It's actually with responsive navbar which uses the collapse
plug-in. Here's some sample HTML (which I should've included in the first
place, sorry about that):

``` html

<nav class="header-navbar">
     <div class="navbar">
                    <div class="navbar-inner">
                        <div class="container-fluid">
                            <a href="" class="btn btn-primary pull-right
btn-donate hidden-phone">
                                Donate Today <i class="icon-chevron-right
icon-white"></i>
                            </a>

                            <a href="" class="btn btn-primary btn-donate
pull-right visible-phone">
                                Donate Today <i class="icon-chevron-right
icon-white"></i>
                            </a>

                            <!-- .btn-navbar is used as the toggle for
collapsed navbar content -->
                            <a class="btn btn-navbar"
data-target=".navbar-responsive-collapse" data-toggle="collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </a>

                            <div class="nav-collapse collapse
navbar-responsive-collapse">
                                #displayModule('Smart Navigation')#
                            </div>
                        </div>
                    </div>
                </div>
</nav>

```

This would normally work right out of the box with the jQuery
implementation. I've reviewed my mark-up against the sample mark-up on the
Twitter Bootstrap components page and don't see anything wrong. So I'm not
quite sure what I'm doing wrong here.

However, when I instantiate the collapsible nav area by adding an ID to the
"nav-collapse" div where the navigation is dynamically output and adding
the "new Boostrap.Collapse($('mobileNav'));" command to a javascript block
towards the top of the page, it does sort of work, but incorrectly. It
defaults to having that collapsed responsive navbar open, it won't close,
and it only allows partial display of the children within each root menu
item.

I really wish I could push it up to our staging server for you to actually
see, but unfortunately I'm not at a point where I can do that just yet.

Any input you might have is definitely appreciated!

Rick

PS: I'm sorry for contacting  you like this, I did try hitting up Stack
Overflow first, but couldn't find anything specific to your port.

**Comment by jwestbrook** [comment]
No worries - I opened a new issue #2 

I put the HTML you provided up on the testing ground and it doesnt seem to work but without the rest of the html I'm kinda stuck

Any way you could post some of the rendered HTML for me over on the new issue?

Also side note I did interpret the targeting to ONLY use ID's but that's my bad - which is why it probably didn't work initially - I'll be fixing that with this issue.

Thanks!

**Comment by HeyWrecker** [comment]
Thanks Jason.

I pulled the rendered HTML for the menu and am attaching it to this email.
As far as I can tell, everything is correct. Now, there is a style block
there that I think gets added in dynamically by BS because it's not in my
pre-rendered source. But, otherwise that should be it. Let me know if
there's anything else I can help with!

Rick
