### ISSUE TITLE
Strange character in code ~

### ISSUE THREAD

**Issue by kstubs** [jwestbrook/bootstrap-prototype#15]
Is this a typo, the 1st else if statement leads with a ~.  This is found in bootstrap-typehead_prototype.js.

```
while (item = items.shift()) {
if (!item.toLowerCase().indexOf(this.query.toLowerCase())) beginswith.push(item);
  else if (~item.indexOf(this.query)) caseSensitive.push(item);
  else caseInsensitive.push(item);
}
```

**Comment by kstubs** [comment]
Never mind.  This is a bitwise not operator (if that is what is expected here).

**Comment by jwestbrook** [comment]
yep directly used from original bootstrap code
