### ISSUE TITLE
Popover

### ISSUE THREAD

**Issue by jasonVenngo** [jwestbrook/bootstrap-prototype#17]
Hi,  I was hoping you could show be a basic example of how to implement the bootstrap popover using your PrototypeJS based bootstrap.   I have had no luck getting any components working other than a modal.

here's a basic page I'm testing with which you used in another support page.   I've tried even initializing a tooltip using a document.observe but it just throws an error stating that tooltip is not a function.

the modal on this page does work though.

here's a link to the basic page i'm working with: https://app.box.com/s/x8xo5n4j3ytbn5hksotc9ur4c6v4us6h

**Comment by jwestbrook** [comment]
I have an example page where I built all the components here http://cwaadmin.com/bootstrap/

I'll take a look at your example and see if I see anything

**Comment by jasonVenngo** [comment]
thank you for this!  helps big time.

**Comment by kstubs** [comment]
Jason, I tried to run your script but you've deployed to Box and so downloading your samples is not complete, you have relative linked script files that are not found.  Can you instead put up a working sample within your domain or create a jsFiddle?

**Comment by jasonVenngo** [comment]
Hi guys, thank you for your help, I actually got it working by following jwestbrooks example component page, I should have closed this.
