### ISSUE TITLE
BootStrap.Collapse does not respect classes only ID's

### ISSUE THREAD

**Issue by jwestbrook** [jwestbrook/bootstrap-prototype#2]
based on this https://github.com/jwestbrook/bootstrap-prototype/issues/1#issuecomment-18402107

and this html

``` html
<nav class="header-navbar">
     <div class="navbar">
                    <div class="navbar-inner">
                        <div class="container-fluid">
                            <a href="" class="btn btn-primary pull-right
btn-donate hidden-phone">
                                Donate Today <i class="icon-chevron-right
icon-white"></i>
                            </a>

                            <a href="" class="btn btn-primary btn-donate
pull-right visible-phone">
                                Donate Today <i class="icon-chevron-right
icon-white"></i>
                            </a>

                            <!-- .btn-navbar is used as the toggle for
collapsed navbar content -->
                            <a class="btn btn-navbar"
data-target=".navbar-responsive-collapse" data-toggle="collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </a>

                            <div class="nav-collapse collapse
navbar-responsive-collapse">
                                #displayModule('Smart Navigation')#
                            </div>
                        </div>
                    </div>
                </div>
</nav>
```

The collapse component fails to collapse or expand the target element

**Comment by jwestbrook** [comment]
@HeyWrecker sorry nothing was attached to your email

**Comment by HeyWrecker** [comment]
That's bizarre. I wonder if it got filtered out. Here it is inline:

<nav class="header-navbar">
    <div class="navbar">
        <div class="navbar-inner">
            <div class="container-fluid">
                <a class="btn btn-primary pull-right btn-donate
hidden-phone" href="">
                    Donate Today <i class="icon-chevron-right
icon-white"></i>
                </a>

```
            <a class="btn btn-primary btn-donate pull-right
```

visible-phone" href="">
                    Donate Today <i class="icon-chevron-right
icon-white"></i>
                </a>

```
            <!-- .btn-navbar is used as the toggle for collapsed navbar
```

content -->
                <a data-toggle="collapse in"
data-target=".navbar-responsive-collapse" class="btn btn-navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>

```
            <div class="nav-collapse navbar-responsive-collapse in
```

collapse" id="mobileNav" style="height: 217px;">

```
                <style>
                  .navbar-text {
                      padding-left: 20px;
                  }

                  .navbar-text p {
                      line-height: 20px;
                  }

                  .navbar-text small {
                      font-size: 11px;
                  }
                </style>
                <div class="HMenu">
                      <ul class="nav pull-right">
                          <li><a
```

href="/animal_services_dev/306-22925-0/home_page.cfm">Home</a></li>

```
                        <li class="dropdown">
                            <a href="#" data-toggle="dropdown"
```

class="dropdown-toggle">
                                    About Us
                                    <b class="caret"></b>
                                </a>
                                  <ul class="dropdown-menu span5">
                                     <li>
                                        <a
href="/animal_services_dev/306-22933-22928/contact_information.cfm">Contact
Information</a>
                                              <div class="navbar-text">
                                                  <p>Get in touch with us
by phone or stop on by!</p>
                                              </div>
                                      </li>

```
                                   <li>

                                      <a
```

href="/animal_services_dev/306-22933-23044/our_stories.cfm">Our Stories</a>
                                        <div class="navbar-text">
                                            <p>At Osceola County Animal
Services, we are thrilled when pets find their forever families. Read on
for some of our special adoption stories!</p>
                                          </div>
                                      </li>

```
                              </ul>
                          </li>

                        <li class="dropdown">
                            <a href="#" data-toggle="dropdown"
```

class="dropdown-toggle">
                                    Find a Pet
                                    <b class="caret"></b>
                                  </a>
                                  <ul class="dropdown-menu span5">
                                     <li>
                                        <a
href="/animal_services_dev/306-22930-22988/adoptable_pet_search.cfm">
                                            Adoptable Pet Search
                                        </a>
                                          <div class="navbar-text">
                                              <p>We have made available a
listing of all of our dogs and cats that are available for adoption.&nbsp;
All animals are available right now and you can take a look at pictures and
descriptions for these wonderful animals before coming down.&nbsp; If you
have questions about adoption, please see our FAQ on pet adoption.</p>
                                          </div>
                                      </li>

```
                                   <li>

                                      <a
```

href="/animal_services_dev/306-22930-22927/pets_of_the_week.cfm">Pets of
the Week</a>
                                          <div class="navbar-text">
                                              <p>Looking for a new friend?
Watch some of our guests in action!</p>
                                          </div>
                                      </li>

```
                                  <li>
                                    <a
```

href="/animal_services_dev/306-22930-23050/steps_to_take_if_youve_lost_a_pet.cfm">
                                            Steps to Take If You've Lost a
Pet
                                        </a>
                                          <div class="navbar-text">
                                              <p>If you've lost a pet,
don't give up too quickly. We've got some tips that can help!</p>
                                          </div>
                                      </li>

```
                              </ul>
                          </li>

                        <li class="dropdown">
                            <a href="#" data-toggle="dropdown"
```

class="dropdown-toggle">
                                    Learning Center
                                      <b class="caret"></b>
                                  </a>
                                  <ul class="dropdown-menu span5">
                                    <li>
                                        <a
href="/animal_services_dev/306-22932-22936/dog_training_and_behavior.cfm">
                                            Dog Training and Behavior
                                        </a>
                                        <div class="navbar-text">
                                            <p>Learn the benefits of
training your dog through positive reinforcement.</p>
                                          </div>
                                      </li>

```
                                   <li>
                                    <a
```

href="/animal_services_dev/306-22932-22960/frequent_questions.cfm">
                                            Frequent Questions
                                        </a>
                                          <div class="navbar-text">
                                              <p>Have questions about
Animal Services? Check out our FAQ!</p>
                                          </div>
                                      </li>

```
                                   <li>
                                    <a
```

href="/animal_services_dev/306-22932-22937/housetraining_101.cfm">
                                            Housetraining 101
                                        </a>
                                          <div class="navbar-text">
                                              <p>The key to training your
dog to eliminate outside (where you want him to) is to prevent accidents,
and to reward success. Learn more about through this informative article by
Sue Sternberg.</p>
                                          </div>
                                      </li>

```
                                   <li>
                                    <a
```

href="/animal_services_dev/306-22932-22950/online_resources.cfm">
                                            Online Resources
                                        </a>
                                          <div class="navbar-text">
                                              <p>Didn't find what you were
looking for through us? Try our collection of invaluable links to other
online resources!</p>
                                          </div>
                                      </li>

```
                                   <li>
                                    <a
```

href="/animal_services_dev/306-22932-22938/pet_safety.cfm">
                                            Pet Safety
                                        </a>
                                          <div class="navbar-text">
                                              <p>Must-read information for
any responsible pet owner.</p>
                                          </div>
                                      </li>

```
                                   <li>
                                    <a
```

href="/animal_services_dev/306-22932-23039/rescue.cfm">
                                            Rescue
                                        </a>
                                          <div class="navbar-text">
                                              <p>Sometimes we receive pets
that we simply cannot hold onto, either due to a medical or behavioral
condition. Our rescue partners help to fill that gap.</p>
                                          </div>
                                      </li>
                                  </ul>
                              </li>

```
                        <li class="dropdown">
                            <a href="#" data-toggle="dropdown"
```

class="dropdown-toggle">
                                      Our Services
                                      <b class="caret"></b>
                                  </a>
                                  <ul class="dropdown-menu span5">
                                     <li>
                                        <a
href="/animal_services_dev/306-22934-22941/adoption.cfm">
                                            Adoption
                                        </a>
                                          <div class="navbar-text">
                                              <p>Interested in adopting?
Read these important notes first.</p>
                                          </div>
                                      </li>

```
                                   <li>
                                    <a
```

href="/animal_services_dev/306-22934-22943/animal_traps.cfm">
                                            Animal Traps
                                        </a>
                                          <div class="navbar-text">
                                              <p>Need to trap a nuisance
animal? Learn about our trap loan service.</p>
                                          </div>
                                      </li>

```
                                   <li>
                                    <a
```

href="/animal_services_dev/306-22934-22945/citations.cfm">
                                            Citations
                                        </a>
                                          <div class="navbar-text">
                                              <p>Learn more about what can
land you a citation and how much it will cost.</p>
                                          </div>
                                      </li>

```
                                   <li>
                                    <a
```

href="/animal_services_dev/306-22934-22948/county_license_tags.cfm">
                                            County License Tags
                                        </a>
                                          <div class="navbar-text">
                                              <p>Get your pet licensed!
Read our county tagging requirements.</p>
                                          </div>
                                      </li>
                                  </ul>
                              </li>

```
                        <li class="dropdown">
                              <a href="#" data-toggle="dropdown"
```

class="dropdown-toggle">
                                      Volunteering
                                      <b class="caret"></b>
                                  </a>
                                  <ul class="dropdown-menu span5">
                                     <li>
                                        <a
href="/animal_services_dev/306-23024-23025/volunteer_forms.cfm">
                                            Volunteer Forms
                                        </a>
                                          <div class="navbar-text">
                                              Want to volunteer with us?
Grab your forms and get started!
                                          </div>
                                      </li>

```
                                   <li>
                                    <a
```

href="/animal_services_dev/306-23024-22931/volunteer_guide.cfm">
                                            Volunteer Guide
                                        </a>
                                          <div class="navbar-text">
                                              <p>Read up on our volunteer
process!</p>
                                          </div>
                                      </li>
                                  </ul>
                              </li>
                          </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>

**Comment by jwestbrook** [comment]
I was able to replicate your issue (as soon as I realized that I needed to use a mobile device) and I'm working on it. It's strange why it doesn't work. I should have something for you by the end of the weekend.

**Comment by HeyWrecker** [comment]
Awesome, thanks Jason. I was able to replicate it both on mobile and just
through screen resizing, if that helps.

I really appreciate it man! Do you work on Bootstrap for Twitter or did you
fork the original?

Rick

**Comment by jwestbrook** [comment]
OK I got this all fixed up for you.

I put the example HTML on this page which shows it working now
http://www.cwaadmin.com/bootstrap/test.html

Please pull the latest compiled JS file 
https://github.com/jwestbrook/bootstrap-prototype/blob/master/js/bootstrap_prototype.js 
or just the component file - whichever you need.

Please confirm everything is working for you and then we can close the issue.

Actually I forked it more to provide the awesomeness for devs that prefer to work with PrototypeJS (as I do) and don't want to load another library just to get everything working. Plus I added the backwards compatibility to support IE less than 10 for all the CSS transitions.

**Comment by HeyWrecker** [comment]
Awesome, thanks for working on this. Quick question though, is it assigning
a fixed height to the responsive nav collapsible area? The native jQuery
version expands the collapsible area to fit all of the second tier menu
items. However, in the demo it appears to have a fixed height and as a
result is cropping out the majority of the second tier menu items.

As for the fork, I don't know if you've had anybody else thank you for the
work you've done on it, but count me as somebody who is very appreciative.
Our in-house CMS was built using PrototypeJS and Scriptaculous on the
front-end, which up until now, had not been conducive to working with
Bootstrap. Up until I found your fork, I was simply working on making
jQuery and PrototypeJS co-exist peacefully. Which, is certainly possible,
but just like you said, why load an extra library if you don't need to.

So thanks! Your work has made my life creating a modern theme for our four
year old CMS so much easier. I hope you have a great weekend Jason!

Rick

**Comment by jwestbrook** [comment]
I know I assigned the static height so that the Scriptaculous Effects would work correctly - let me see abound tweaking it so that it will expand like you are referring to.

Thanks for the support - I hope I hear from more devs like you.

**Comment by HeyWrecker** [comment]
Thanks Jason. The other thing that I noticed is that due to the static
height, the menu defaults to open rather than defaulting to closed and
requiring an action to open it.

**Comment by jwestbrook** [comment]
In the original HTML you posted you had a style set on the collapsing div - if you take that off - it should start closed.

**Comment by HeyWrecker** [comment]
Yep, that was the problem. It was hard coded in there for development
purposes. Once you pointed that out, I moved it into my css file. Derp. All
that remains is dynamic resizing of the mobile menu so that all of the
sub-menu items display.

**Comment by HeyWrecker** [comment]
Jason, in order to meet my deadline for the website I've been developing using your library, I made the following change to my local copy of the bootstrap-collapse_prototype.js file near line 98. I replaced this code:

newstyle[dimension] = this.$element[scroll]+'px'

With this:

newstyle[dimension] = 'auto'

As best as I can tell, that resolved my issue of the menu not dynamically expanding to include the second tier menu items. I haven't noticed any unwanted side effects. Let me know if that works for you as well.

**Comment by HeyWrecker** [comment]
PS: If you want to see my in-production site that I developed that makes use of your Bootstrap PrototypeJS port, hit up www.osceolacountypets.com.

I'm still fine tuning some things. But overall I'm happy with the outcome!

**Comment by jwestbrook** [comment]
No worries - thats what I would have suggested you update for that purpose. I've been extra busy this last week and have not been able to get that fixed for you.

**Comment by HeyWrecker** [comment]
No worries! We all have jobs to do. ;-) Are you on LinkedIn by any chance? If so, look me up- Rick Zawadzki.
