### ISSUE TITLE
Can't get bootstrap-prototype to work. 

### ISSUE THREAD

**Issue by maniacmusic** [jwestbrook/bootstrap-prototype#3]
For some reason I just can't get your version of Bootstrap to work. Is it required to use other files than bootstrap_prototype.min.js ?
I'm working on a Bootstrap based theme framework for MyBB 1.6 which is Prototype based and I have some trouble with jQuery conflicts.

**Comment by jwestbrook** [comment]
You need the CSS file and prototype.js as well - but that should work. Do you get any JS errors?

Take a look at this page - I have examples of all the modules running

http://www.cwaadmin.com/bootstrap/

**Comment by maniacmusic** [comment]
I have the Bootstrap CSS included. Can you take a look at my website? http://openskin.mrpg.me/

**Comment by jwestbrook** [comment]
OK you have a javascript error that is referring to the collapse module -
the button is missing a href attribute as the target

It should work with the data-target attribute as well - I'll get a fix into
that file for you today

In the mean time if you use

href=".nav-collapse"

instead of data-target it should start working

Jason Westbrook | T: 313-799-3770 | jwestbrook@gmail.com

**Comment by maniacmusic** [comment]
I think I will wait for the patch. Thank you very much!

**Comment by igniansoft** [comment]
Thanks :)

**Comment by jwestbrook** [comment]
OK files all committed - let me know if that works for you

**Comment by maniacmusic** [comment]
Everything that toggles seems to be working great! Do the tooltips require special mark up though? The forums should show a tooltip containing the forum description.

**Comment by jwestbrook** [comment]
Tooltips and Popovers need to be created - they won't just happen if you add the right attributes

I think you can do it like this

``` javascript
$$('.forumbitForumDescription').each(function(e){
    new BootStrap.Tooltip(e);
});
```

I tried it on your page by manually running this code and the positioning of the tooltips is down by 10-30px I'll see what I can do to fix that

**Comment by maniacmusic** [comment]
Thanks. :)
The offset seems to get bigger the deeper you get down - for me it's much more than just 10-30px.

**Comment by maniacmusic** [comment]
Did you forget about this? 
Tooltips are still broken....

**Comment by jwestbrook** [comment]
Sorry I haven't forgot about it - I'm still trying to recreate the problem so I can play with it and hopefully fix it.

**Comment by jwestbrook** [comment]
@maniacmusic OK I've found the problem and working on a solution - I didn't expect the positioning to break when inside a relatively positioned container - but I'm going to detect for that and adjust - I'll have a fix for you today

**Comment by jwestbrook** [comment]
@maniacmusic please update your files and let me know if that fixed the problem. If so please close the issue

Thanks!

**Comment by maniacmusic** [comment]
Thanks a lot.
