### ISSUE TITLE
Modals and programatically closing them

### ISSUE THREAD

**Issue by iantearle** [jwestbrook/bootstrap-prototype#4]
Hi, I have a modal that is launched from an anchor, the contents of it is a form that fires ajax request. On complete / success I wish to fire a close on the modal, cant figure out how to do it, I've tried all the examples (I think) - I could be missing something, how would you do it?

**Comment by iantearle** [comment]
Have actually managed to achieve what I wanted to do with:

```
$(element).retrieve('bootstrap:modal').hide();
```

**Comment by jwestbrook** [comment]
That is exactly how it is designed to work. Let me know if you have any other questions.

**Comment by iantearle** [comment]
lol ok. Thanks for clarifying. Been a long time since I played with prototype...
