### ISSUE TITLE
Navbar dropdown animation broken

### ISSUE THREAD

**Issue by maniacmusic** [jwestbrook/bootstrap-prototype#5]
Since the tooltip fix, the navbar animation stopped working.

**Comment by jwestbrook** [comment]
Which dropdown animation are you referring to? There are no CSS transitions in the dropdown component library. And I can't find any examples where there is an animation

**Comment by maniacmusic** [comment]
The animation that should appear when you click here......... http://i.imgur.com/oSidazA.png

**Comment by jwestbrook** [comment]
OK that is actually part of the collapse component - and I think I had left some statement commented out - fixing it right now.

**Comment by maniacmusic** [comment]
Thanks again! 
:+1:
