### ISSUE TITLE
carousel switching not working with carousel-indicators

### ISSUE THREAD

**Issue by mcinp** [jwestbrook/bootstrap-prototype#7]
Switching of carousel slides does not work - neither from JS (using .to() method) nor by using .carousel-indicators.
I tried to commit a fix to that but obviosly I'm not allowed to.

The bugs were (in bootstrap-carousel_prototype.js):
1) in the document.observe('dom:loaded',function()) (line 201)
"to" variable was null when clicked on .carousel-indicators element, thus calling <code>$target.retrieve('bootstrap:carousel')[to]()</code> on line 209 resulted in error

2) the Element.select method returns an array, so variable $active on line 73 becomes an array and subsequent calls to $active as if it was an object produced errors on lines 74 and 75 

3) There was a typo on line 75 (children.index instead of children.indexOf)

below are links to diff and resulting file:

https://aionet.eu/bs-proto/carousel.patch

https://aionet.eu/bs-proto/bootstrap-carousel_prototype.js

Thank you for your tremendous work with bootstrap-prototype Jason !

**Comment by jwestbrook** [comment]
Thanks for the patch file and the digging! Please confirm the updates fix the bugs you found.

**Comment by mcinp** [comment]
yes they seem to be working properly
