### ISSUE TITLE
relying on Scriptaculous !== 'undefined' leads to transition not working

### ISSUE THREAD

**Issue by mcinp** [jwestbrook/bootstrap-prototype#8]
In bootstrap-transition_prototype.js on line 59 following code is used to determine if Scriptaculous library is loaded
<code>typeof Scriptaculous !== 'undefined' && typeof Effect !== 'undefined'</code>
there is however a possibility that effects.js is loaded but scriptaculous.js is not, This can happen if
1. someone manually loads appropriate js components from scriptaculous without using scriptaculous.js
2. the loading of scriptaculous files is managed programatically (that's how it's done in Prado framework)

my suggestion is to remove the <code>typeof Scriptaculous !== 'undefined'</code> and leave only <code>typeof Effect !== 'undefined'</code>

I tested it to work properly on IE8 & IE9

**Comment by jwestbrook** [comment]
Actually a good suggestion - are you able to fork the repo and create a Pull Request for this change? - I want to give credit where credit is due.

Thanks!

**Comment by mcinp** [comment]
as to Pull Request - thank you for the proposal - maybe next time
